### ISSUE TITLE
Impossible to use the plugin with custom IAM endpoint and an HTTP proxy

### ISSUE THREAD

**Issue by mhobnp** [ibm-cloud-security/vault-plugin-secrets-ibmcloud#22]
Hello, 

we are facing a problem following the use of the plugin with a custom IAM endpoint using VIP.  Our custom endpoint is an F5 virtual IP for interaction with IBM private endpoints.

When creating the role and validating the token JWT, the OIDC configuration is retrieved at `https://$OUR_CUSTOM_DOMAIN/identity/.well-known/openid-configuration` we retrieve an "incorrect" payload.

```json
{
    "issuer": "https://iam.cloud.ibm.com/identity",
    "authorization_endpoint": "https://private.iam.cloud.ibm.com/identity/authorize",
    "token_endpoint": "https://private.iam.cloud.ibm.com/identity/token",
    "passcode_endpoint": "https://private.iam.cloud.ibm.com/identity/passcode",
    "userinfo_endpoint": "https://private.iam.cloud.ibm.com/identity/userinfo",
    "jwks_uri": "https://private.iam.cloud.ibm.com/identity/keys",
    "response_types_supported": [
        "code",
        "id_token",
        "token id_token"
    ],
    "grant_types_supported": [
        "implicit",
        "authorization_code",
        "password",
        "refresh_token",
        "urn:ibm:params:oauth:grant-type:apikey",
        "urn:ibm:params:oauth:grant-type:identity-cookie",
        "urn:ibm:params:oauth:grant-type:iam-cookie",
        "urn:ibm:params:oauth:grant-type:delegated-refresh-token",
        "urn:ibm:params:oauth:grant-type:ims-portal",
        "urn:ibm:params:oauth:grant-type:iam-authz",
        "urn:ibm:params:oauth:grant-type:derive"
    ],
    "subject_types_supported": [
        "public"
    ],
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "scopes_supported": [
        "openid",
        "email",
        "profile",
        "ibm",
        "roles",
        "containers-kubernetes",
        "containers-openshift"
    ],
    "claims_supported": [
        "iam_id",
        "sub",
        "aud",
        "iss"
    ],
    "public_hosts": [
        ...
    ]
}
```

However, when the plugin tries to validate the key it uses `https://private.iam.cloud.ibm.com/identity/keys` instead of our VIP's IP `https://$OUR_CUSTOM_DOMAIN/identity/keys`. This domain is inaccessible, so it is impossible for us to use the plugin as it stands.

I think some of the implementation of the plugin is missing when using a custom endpoint.

One solution could be to have the ability to override the OIDC configuration and not rely on the return of the endpoint `https://$OUR_CUSTOM_DOMAIN/identity/.well-known/openid-configuration`.

**Comment by smatzek** [comment]
Can you please provide the error messages you receive from the vault client and server sides?

**Comment by mhobnp** [comment]
Yes. I have the following error when I watch the vault monitor

`{"@level":"error","@message":"error obtaining the token for the configured API key","@module":"secrets.vault-plugin-secrets-ibmcloud.vault-plugin-secrets-ibmcloud_f141d469.vault-plugin-secrets-ibmcloud.vault-plugin-secrets-ibmcloud","@timestamp":"2022-07-26T14:26:12.154876+02:00","error":"an error occurred verifying the token failed to verify signature: fetching keys context canceled","timestamp":"2022-07-26T14:26:12.154+0200"}`

and the following error from vault API

`"an error occurred verifying the token failed to verify signature: fetching keys oidc: get keys failed Get \"[https://private.iam.cloud.ibm.com/identity/keys\":](https://private.iam.cloud.ibm.com/identity/keys/%22:) dial tcp 166.9.251.2:443: i/o timeout` .
