### ISSUE TITLE
Documented build process fails for vault plugin with current golang 1.15

### ISSUE THREAD

**Issue by priyanknarvekar** [ibm-cloud-security/vault-plugin-secrets-ibmcloud#4]
It appears that as of golang 1.15, the arch support for `darwin/386` was removed (https://github.com/golang/go/issues/37610)

Documentation does not indicate the golang version it has been tested with.

**We need to document the golang version that the code and build process has been tested with and/or update the build scripts to not build for arch `darwin/386`**

**Comment by smatzek** [comment]
In my testing I used Go 1.14.2 and Vault 1.5.0.

The build scripts match what is in the GCP and Azure plugins, which do contain "darwin/386". The build process used to build Vault, which pulls in the plugins and builds them is setting up the arch differently than how it defaults when called by make.

I can recreate this problem at Go 1.15.5. To build this with Go 1.15.5, remove "darwin/386" from
https://github.com/ibm-cloud-security/vault-plugin-secrets-ibmcloud/blob/main/scripts/build.sh#L26

**Comment by smatzek** [comment]
Another, simpler workaround is to run `make dev` which will build the binary for your local architecture and will skip all of the others, including the problematic `darwin/386` arch.

**Comment by priyanknarvekar** [comment]
@smatzek , understand gcp/azure still have it in their scripts and understand the workaround, thats what we have used it for now. 
intention of this issue was to either 
- get the build.sh updated based on go version and/OR
- get our Readme.md updated as a known issue and Go version supported
 we need to atleast update our Readme and document the Go version

**Comment by smatzek** [comment]
@priyanknarvekar Above I was documenting workarounds and versions I used during dev/test so that others that hit the same issue know their options while we work on the fix and test it. I agree that a fix to the README and build scripts is needed which is why I did not close the issue after commenting above.

**Comment by smatzek** [comment]
Fix by #6
