### ISSUE TITLE
Error when enabling the plugin

### ISSUE THREAD

**Issue by chihebeddine** [ibm-cloud-security/vault-plugin-secrets-ibmcloud#9]
I am trying to add the IBM secrets plugin to Vault but have an issue enabling it:

- vault version: v1.6.1+ent.hsm
- plugin version: v0.1.0

the plugin is added successfuly using the vault register command:

`vault plugin register -sha256=${SHA256} secret vault-plugin-secrets-ibmcloud`

But when trying to mount the lugin, i receive the following error message:

`vault secrets enable -plugin-name="vault-plugin-secrets-ibmcloud" -path="ibmcloud" plugin`

```
* Unrecognised remote plugin message:
This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

**Comment by smatzek** [comment]
I tried this with v1.6.1+ent.hsm running in dev mode and I cannot recreate it. I also cannot recreate in 1.6.1.

I in searches, I have found other reports of this message on other plugins but there is no concise description on how it was avoided:
https://github.com/mongodb/vault-plugin-secrets-mongodbatlas/issues/21
https://github.com/immutability-io/vault-ethereum/issues/66

Can you share other messages from your Vault server log?
Does this recreate for you in with regular 1.6.1?
Does it recreate when the server is run in dev mode?

In this issue, the individual who opened the issue self-closed it after seeing some other messages in the system journal:
https://github.com/mongodb/vault-plugin-secrets-mongodbatlas/issues/21#issuecomment-551196158

**Comment by chihebeddine** [comment]
Indeed, I tried to reproduce with Vault version v1.6.1+ent.hsm in dev mode (worked with no issues).
Of course, we do not run Vault in dev mode in a production env. Vault is in HA mode with three nodes, IBM plugins placed in the plugin dir in all three servers.

There are no message apart from the one reported in the server logs.
We have Vault ent+hsm so I can't 
Works OK in dev mode.

I have seen the other issues before posting this one, I see nothing concrete in them.
Please let me know if you need further info.

**Comment by smatzek** [comment]
@motyd gave me some tips on this issue as well.

The `api_addr ` parameter must be set in the config when not running in dev mode in order for custom backends to mount successfully: https://www.vaultproject.io/docs/configuration#api_addr

You mention that your Vault is in HA mode already. Do you have that parameter set?

**Comment by chihebeddine** [comment]
The `api_addr` paramater is set in all servers (set to `https://server_fqdn:8200`)

**Comment by murkyl** [comment]
I ran into this problem as well on a plugin I am developing. Check the permission on the plugin binary. See if the vault process has read and execute permissions on the binary. Fixing this solved my problem.
e.g.
chown vault:vault /etc/vault.d/vault_plugins/<plugin_name>
chmod 750 /etc/vault.d/vault_plugins/<plugin_name>

**Comment by smatzek** [comment]
It seems the root cause of this was likely permissions so I am closing this out.
